name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: eco-folder-438813-f0
      REGION: us-central1
      SERVICE: my-node-app-deployer
      REPOSITORY: my-repo
      IMAGE: us-central1-docker.pkg.dev/eco-folder-438813-f0/my-repo/my-node-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: docker build -t $IMAGE:$GITHUB_SHA .

    - name: Push Docker image to Artifact Registry
      run: docker push $IMAGE:$GITHUB_SHA

    - name: Deploy to Cloud Run (manual command)
      run: |
        gcloud run deploy $SERVICE \
          --image=$IMAGE:$GITHUB_SHA \
          --region=$REGION \
          --platform=managed \
          --allow-unauthenticated \
          --project=$PROJECT_ID
