name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-node-app:$GITHUB_SHA"
        docker build -t $IMAGE .
        docker push $IMAGE
      env:
        GCP_REGION: ${{ secrets.GCP_REGION }}
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

    - name: Deploy to Cloud Run
      run: |
        IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-repo/my-node-app:$GITHUB_SHA"
        gcloud run deploy my-node-app \
          --image=$IMAGE \
          --platform=managed \
          --region=${{ secrets.GCP_REGION }} \
          --project=${{ secrets.GCP_PROJECT }} \
          --allow-unauthenticated
